const CACHE="calc-rpg-v20";
const CORE=["./","./index.html","./manifest.webmanifest","./icon-180.png","./icon-192.png","./icon-512.png"];
const TIERS=["leather","stone","iron","diamond","nether"];
const PARTS=["weapon","head","body","legs","feet"];
const BOSS_ASSETS=TIERS.map(t=>`./assets/bosses/boss_${t}.webp`);
const ENEMY_ASSETS=["slime","goblin","wolf","bat","mushroom"].map(e=>`./assets/enemies/enemy_${e}.webp`);
const SOUND_ASSETS=["./assets/sounds/digit.mp3","./assets/sounds/confirm.mp3"];
const UI_ASSETS=["./assets/ui/battle-bg-clean.webp","./assets/ui/result-backdrop.webp","./assets/ui/hero-scene.webp","./assets/ui/hero-home.webp","./assets/ui/hero-battle.webp","./assets/ui/title-logo.webp"];
const ASSETS=CORE.concat(TIERS.flatMap(t=>PARTS.map(p=>`./eq_${t}_${p}.png`)),BOSS_ASSETS,ENEMY_ASSETS,SOUND_ASSETS,UI_ASSETS);
self.addEventListener("install",event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener("activate",event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match("./index.html"))))});
